#!/bin/sh

"$AMSBIN/ams" << eor

Task MolecularDynamics
MolecularDynamics
    NSteps 20000
    TimeStep 0.25
    Trajectory
        SamplingFreq 400
    End
    Checkpoint
        Frequency 20000
    End
    InitialVelocities
        Temperature 300
    End
    Thermostat
        Type Berendsen
        Temperature 300
        Tau 100
    End
End
System
    GeometryFile initial.rkf

    Charge 0.0
End


Engine ReaxFF
    ForceField CHOCsKNaClIFLi.ff
EndEngine

