#!/bin/bash
#SBATCH --time=2-00:00:00
#SBATCH --job-name=NaCl.TEST              # Job name
#SBATCH --nodes=1                        # Number of nodes
#SBATCH --ntasks-per-node=8            # Number of processes per node
#SBATCH --cpus-per-task=8
#SBATCH --error=slurm-%j.err             # SLURM error
#SBATCH --output=slurm-%j.out            # SLURM output

source ~/.bashrc
deactivate
module purge
module load 2023
module load AMS/2024.103-intelmpi
deactivate
mamba activate molmod 

export SCM_TMPDIR=$TMPDIR
export TERM=xterm

# Run an infRETIS calculations
export SCM_DISABLE_MPI=1 # use RETIS MPI
export OMP_NUM_THREADS=8
#When running on multiple nodes we recommend using pure MPI. To this end, set the OMP_NUM_THREADS environment variable to 1 and set other MPI-related option
export AMS_COPYSTATE_MOVES_RESULTS=1

chmod +x restartinit.sh
./restartinit.sh
  # chmod +x runinit.sh
#  ./runinit.sh

